// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO5lohiGy_93Pr8yj_7mcqW7-2GIpecRU',
    appId: '1:95447117348:web:47c845d94a2f1529e572b1',
    messagingSenderId: '95447117348',
    projectId: 'ditonton-9a9f9',
    authDomain: 'ditonton-9a9f9.firebaseapp.com',
    storageBucket: 'ditonton-9a9f9.appspot.com',
    measurementId: 'G-98H4CEH127',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0yWrkOj3DFd-ULiYywKXElllfFUf0YdE',
    appId: '1:95447117348:android:e74f494a1b7c406ee572b1',
    messagingSenderId: '95447117348',
    projectId: 'ditonton-9a9f9',
    storageBucket: 'ditonton-9a9f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4brP4opVesRvFeW99GuCNuG9BUzV0HVk',
    appId: '1:95447117348:ios:1efaf62ee101fd48e572b1',
    messagingSenderId: '95447117348',
    projectId: 'ditonton-9a9f9',
    storageBucket: 'ditonton-9a9f9.appspot.com',
    iosClientId: '95447117348-n98n03q4c34e34vo9c8ucvabr1j7fleb.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
